# spring配置
spring:
    datasource:
        druid:
            stat-view-servlet:
                enabled: true
                loginUsername: ruoyi
                loginPassword: 123456
        dynamic:
            druid:
                initial-size: 5
                min-idle: 5
                maxActive: 20
                maxWait: 60000
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: SELECT 1 FROM DUAL
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxPoolPreparedStatementPerConnectionSize: 20
                filters: stat,slf4j
                connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
                # 初始连接数
                initialSize: 5
                # 最小连接池数量
                minIdle: 10
                # 配置连接超时时间
                connectTimeout: 30000
                # 配置网络超时时间
                socketTimeout: 60000
                # 配置一个连接在池中最大生存的时间，单位是毫秒
                maxEvictableIdleTimeMillis: 900000
                webStatFilter:
                    enabled: true
                statViewServlet:
                    enabled: true
                    # 设置白名单，不填则允许所有访问
                    allow:
                    url-pattern: /druid/*
                    # 控制台管理用户名和密码
                    login-username: ruoyi
                    login-password: 123456
                filter:
                    stat:
                        enabled: true
                        # 慢SQL记录
                        log-slow-sql: true
                        slow-sql-millis: 1000
                        merge-sql: true
                    wall:
                        config:
                            multi-statement-allow: true
            datasource:
                # 主库数据源
                master:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    #生产配置
                    #url: jdbc:mysql://127.0.0.1:3306/cmc_fws_open?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    #username: cmc_fws_open
                    #password: 123456
                    #测试环境
                    url: jdbc:mysql://192.168.0.153:3306/cmc_fws_open?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    username: root
                    password: 123456
